# fly.toml app configuration file generated for viperball on 2026-02-21T00:14:12Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'viperball'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[checks]
  [checks.alive]
    type = "tcp"
    port = 8080
    interval = "30s"
    timeout = "10s"
    grace_period = "120s"

[[vm]]
  size = "performance-1x"
  memory = "2048mb"
